# Generated by Django 4.0.2 on 2022-04-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='duration_in_days',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='travel',
            name='guide_language',
            field=models.CharField(blank=True, choices=[('Unknown_local', 'Unknown_local'), ('Chinese', 'Chinese'), ('Latin', 'Latin'), ('Sanskrit', 'Sanskrit')], max_length=20, null=True),
        ),
    ]
