# Generated by Django 4.0.2 on 2022-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_travel_description_travel_duration_in_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
