# Generated by Django 4.0.2 on 2022-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_travel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='duration_in_days',
            field=models.IntegerField(),
        ),
    ]
