# Generated by Django 4.0.2 on 2022-04-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_travel_duration_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='guide_language',
            field=models.CharField(blank=True, choices=[('Unknown local', 'Unknown local'), ('Chinese', 'Chinese'), ('Latin', 'Latin'), ('Sanskrit', 'Sanskrit')], max_length=20, null=True),
        ),
    ]
