# Generated by Django 4.0.2 on 2022-05-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_travel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='country',
        ),
        migrations.AddField(
            model_name='travel',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='viewer.Country'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='guide_language',
            field=models.CharField(blank=True, choices=[('Unknown local', 'Unknown local'), ('Chinese', 'Chinese'), ('Latin', 'Latin'), ('Sanskrit', 'Sanskrit'), ('No talking!', 'No talking!')], max_length=20, null=True),
        ),
    ]
