# Generated by Django 4.0.2 on 2022-05-08 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0008_remove_travel_country_travel_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('alergic', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='travel',
            name='guide_language',
            field=models.CharField(blank=True, choices=[('Unknown local', 'Unknown local'), ('Chinese', 'Chinese'), ('Latin', 'Latin'), ('Sanskrit', 'Sanskrit'), ('No talking!', 'No talking!'), ('Mostly just cursing', 'Mostly just cursing')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_starts', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.profile')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.travel')),
            ],
        ),
    ]
