# Generated by Django 4.0.2 on 2022-05-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_profile_alter_travel_guide_language_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='num_starts',
        ),
        migrations.AddField(
            model_name='rate',
            name='num_stars',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
