# Generated by Django 4.0.2 on 2022-05-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_profile_favorite_travels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='country',
        ),
        migrations.AddField(
            model_name='travel',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
